FROM golang:1.24-alpine
WORKDIR /app

RUN go install github.com/air-verse/air@latest
RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN swag init -g ./cmd/api/main.go -o ./docs --outputTypes go

EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
